Pytorch Fundamentals

Resources: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.10.0+cpu


In [3]:
!nvidia-smi

Mon May  4 23:17:59 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Introduction to tensors

## Creating tensors

PyTorch tensors are created using 'torch.tensor()' : https://docs.pytorch.org/docs/stable/tensors.html


In [3]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [15]:
scalar.shape

torch.Size([])

In [5]:
# get tensor back as Python int
scalar.item()

7

In [12]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[0][0]

tensor([1, 2, 3])

In [22]:
TENSOR = torch.tensor([[1, 2, 3],
                       [3, 6, 9],
                      [2, 4, 5]])



In [17]:
TENSOR.ndim

2

In [18]:
TENSOR.shape

torch.Size([3, 3])

In [25]:
torch.tensor([[1., -1.], [1., -1.]])
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
TENSOR = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
TENSOR.shape

torch.Size([2, 3])

In [26]:
torch.zeros([2, 4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [27]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[1][2])
x[0][1] = 8
print(x)

tensor(6)
tensor([[1, 8, 3],
        [4, 5, 6]])


In [28]:
x = torch.tensor([[1]])
x


tensor([[1]])

In [30]:
x.shape

torch.Size([1, 1])

In [31]:
x.item()

1

In [33]:
x = torch.tensor(2.5)
x

tensor(2.5000)

In [34]:
x.item()

2.5

In [35]:
import torch

# Define three 2x3 matrices
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

B = torch.tensor([[7, 8, 9],
                  [10, 11, 12]])

C = torch.tensor([[13, 14, 15],
                  [16, 17, 18]])

# Stack them horizontally (along dim=1, i.e., columns)
H = torch.cat([A, B, C], dim=1)

print(H)
H.shape  # torch.Size([2, 9])

tensor([[ 1,  2,  3,  7,  8,  9, 13, 14, 15],
        [ 4,  5,  6, 10, 11, 12, 16, 17, 18]])


torch.Size([2, 9])

In [38]:
V = torch.cat([A, B, C], dim=0)
print(V)
V.shape

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])


torch.Size([6, 3])

In [48]:
T = torch.stack([A, B, C], dim=0)  # dim=0 means new axis at the front

print(T)
T.shape  # torch.Size([3, 2, 3])

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])


torch.Size([3, 2, 3])

In [49]:
T[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

### Random Tensors

Why random tensors?
They are important because many neural networks begin with random tensors, observe the data, and then adjust those numbers to better represent the data.

Torch random tensors: https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [58]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3, 4)
random_tensor


tensor([[0.2365, 0.4183, 0.0913, 0.4426],
        [0.3659, 0.1658, 0.0955, 0.3836],
        [0.2536, 0.1632, 0.2895, 0.8360]])

In [51]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.4129, 0.5310, 0.0677, 0.7519],
         [0.9368, 0.6996, 0.3581, 0.0739],
         [0.9919, 0.3563, 0.9540, 0.7898]]])

In [52]:
random_tensor.ndim

3

In [57]:
random_tensor = torch.rand(3, 4, 1)
random_tensor

tensor([[[0.8882],
         [0.3837],
         [0.7816],
         [0.6108]],

        [[0.5428],
         [0.2532],
         [0.5976],
         [0.0646]],

        [[0.3657],
         [0.5879],
         [0.7363],
         [0.9134]]])

In [54]:
# create a random tensor with the size similar to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [62]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [63]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [64]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [65]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [68]:
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [73]:
zeros_like = torch.zeros_like(input=one_to_ten)
zeros_like


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [74]:
ones_like = torch.ones_like(input=one_to_ten)
ones_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

''Note'': Tensor datatypes is one of the 3 big errors you’ll run into with PyTorch & deep learning:

  1. Tensors not right datatype
  2. Tensors not right shape
  3. Tensors not on the right device

In [76]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None,       # what datatype is the tensor (e.g. float32 by default for floats)
    device=None,      # what device your tensor is on e.g. GPU, CPU, cuda
    requires_grad=False # track gradient?
)

float_32_tensor

tensor([3., 6., 9.])

In [77]:
float_32_tensor.dtype

torch.float32

In [105]:
float_16_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float16,       # what datatype is the tensor (e.g. float32 by default for floats)
    device=None,      # what device your tensor is on e.g. GPU, CPU, cuda
    requires_grad=False # track gradient?
)

print(f"Datatype of tensor: {float_16_tensor.dtype}")
print(f"Device tensor is on: {float_16_tensor.device}")

Datatype of tensor: torch.float16
Device tensor is on: cpu


In [106]:
product = float_16_tensor * float_32_tensor
# Normally, you might get into error if data types doesn't match
print(f"Datatype of tensor: {product.dtype}")

Datatype of tensor: torch.float32


In [107]:
%%time
2*2

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.44 µs


4

In [109]:
vec = torch.tensor([1,2,3])

In [110]:
vec.shape

torch.Size([3])

In [112]:
torch.matmul(vec,vec)

tensor(14)

In [113]:
vec.unsqueeze(0)

tensor([[1, 2, 3]])

In [114]:
vec.unsqueeze(1)

tensor([[1],
        [2],
        [3]])

In [115]:
torch.matmul(vec.unsqueeze(1),vec.unsqueeze(0))

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])